[package]
name = "summarize"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
ollama-rs = "0.3.2"
tokio = { version = "1.46.1", features = ["full"] }
